# .github/workflows/build.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]
jobs:
  wollok-ts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          git clone https://github.com/uqbar-project/wollok-ts-cli
          cp wollok-ts-cli/.nvmrc .
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      # Execute Gradle commands in GitHub Actions workflows
      - run: |
          cd wollok-ts-cli
          npm install
          npm run build
          mv -r ./build/src ./build
          npm run pack
          cd ..
          ./wollok-ts-cli/dist/wollok-ts-cli-linux-x64 test
        shell: bash
