# .github/workflows/build.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]
jobs:
  wollok-ts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Execute Gradle commands in GitHub Actions workflows
      - run: |
          wget -O wollok-ts-cli https://github.com/uqbar-project/wollok-ts-cli/releases/download/v0.1.0/wollok-ts-cli-linux-x64
          ./wollok-ts-cli test --skipValidations -p ./
        shell: bash
